/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lister les alertes énergétiques */
        get: operations["list_alerts_api_v1_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Obtenir un jeton JWT (flux OAuth2 password)
         * @description Déclare le flux OAuth2 password dans la spécification.
         *
         *     form_data porte le contrat d'entrée (username, password, scope) sans être
         *     exploité : la délivrance réelle du jeton est le périmètre d'EV-12.
         */
        post: operations["create_token_api_v1_auth_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Vérifier la disponibilité de l'API
         * @description Endpoint trivial, réellement implémenté : aucune dépendance externe.
         */
        get: operations["get_health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lister les sites supervisés */
        get: operations["list_sites_api_v1_sites_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sites/{site_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consulter un site */
        get: operations["get_site_api_v1_sites__site_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sites/{site_id}/readings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lister les mesures d'un site sur une fenêtre de temps */
        get: operations["list_readings_api_v1_sites__site_id__readings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sites/{site_id}/readings/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consulter la dernière mesure connue d'un site */
        get: operations["get_latest_reading_api_v1_sites__site_id__readings_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AlertOut
         * @description Alerte énergétique, miroir de l'alerte de l'API Mock IoT.
         */
        AlertOut: {
            /**
             * Alert Id
             * @description Identifiant technique de l'alerte.
             */
            alert_id: string;
            /**
             * Message
             * @description Description de l'alerte fournie par la source.
             */
            message: string;
            /**
             * Severity
             * @description Gravité de l'alerte.
             * @enum {string}
             */
            severity: "low" | "medium" | "high" | "critical";
            /**
             * Site Id
             * @description Identifiant du site concerné par l'alerte.
             */
            site_id: string;
            /**
             * Threshold
             * @description Seuil dont le dépassement a déclenché l'alerte.
             */
            threshold: number;
            /**
             * Timestamp
             * Format: date-time
             * @description Horodatage de déclenchement, ISO 8601 UTC.
             */
            timestamp: string;
            /**
             * Type
             * @description Nature de l'anomalie détectée.
             * @enum {string}
             */
            type: "spike" | "threshold" | "anomaly" | "outage" | "sensor";
            /**
             * Value
             * @description Valeur mesurée ayant déclenché l'alerte.
             */
            value: number;
        };
        /** Body_create_token_api_v1_auth_token_post */
        Body_create_token_api_v1_auth_token_post: {
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
            /** Grant Type */
            grant_type?: string | null;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Username */
            username: string;
        };
        /**
         * EnergyReadingOut
         * @description Mesure énergétique horodatée.
         *
         *     Reprend tous les champs de l'EnergyReading source, complétés par les
         *     colonnes d'imputation propres à notre base TimescaleDB.
         */
        EnergyReadingOut: {
            /**
             * Consumption Kw
             * @description Puissance instantanée mesurée en kilowatts, nulle si absente de la source.
             */
            consumption_kw: number | null;
            /**
             * Consumption Kw Imputed
             * @description Puissance imputée en kilowatts, calculée par l'ETL. Jamais confondue avec consumption_kw qui reste la valeur brute de la source.
             */
            consumption_kw_imputed: number | null;
            /**
             * Consumption Kwh
             * @description Énergie consommée sur le pas de temps en kilowattheures.
             */
            consumption_kwh: number | null;
            /**
             * Current A
             * @description Intensité mesurée en ampères.
             */
            current_a: number | null;
            /**
             * Data Quality
             * @description Qualité de la mesure telle que qualifiée par la source.
             * @enum {string}
             */
            data_quality: "good" | "partial" | "degraded" | "critical";
            /**
             * Humidity Percent
             * @description Humidité relative relevée en pourcentage.
             */
            humidity_percent: number | null;
            /**
             * Imputation Method
             * @description Méthode d'imputation appliquée : none si la mesure brute est exploitable, locf pour un report de la dernière valeur connue, interpolation sinon.
             * @enum {string}
             */
            imputation_method: "none" | "locf" | "interpolation";
            /**
             * Null Reasons
             * @description Motifs fournis par la source pour chaque champ absent de la mesure.
             */
            null_reasons: string[];
            /**
             * Power Factor
             * @description Facteur de puissance mesuré.
             */
            power_factor: number | null;
            /**
             * Site Id
             * @description Identifiant du site auquel la mesure appartient.
             */
            site_id: string;
            /**
             * Site Type
             * @description Catégorie du site, dénormalisée depuis le site.
             */
            site_type: string;
            /**
             * Temperature Celsius
             * @description Température ambiante relevée en degrés Celsius.
             */
            temperature_celsius: number | null;
            /**
             * Timestamp
             * Format: date-time
             * @description Horodatage de la mesure, ISO 8601 UTC.
             */
            timestamp: string;
            /**
             * Voltage V
             * @description Tension mesurée en volts.
             */
            voltage_v: number | null;
        };
        /**
         * ErrorResponse
         * @description Corps de réponse commun à toutes les erreurs de l'API.
         */
        ErrorResponse: {
            /**
             * Detail
             * @description Message d'erreur destiné au consommateur de l'API.
             */
            detail: string;
        };
        /**
         * HealthOut
         * @description État de disponibilité de l'API.
         *
         *     Le brief décrit un dict {status, timestamp} : il est typé ici pour
         *     respecter la convention de projet (description sur chaque champ, valeurs
         *     fermées en Literal) et pour que le dashboard en dérive un type utilisable.
         */
        HealthOut: {
            /**
             * Status
             * @description Statut de l'API, ok si elle répond.
             * @constant
             */
            status: "ok";
            /**
             * Timestamp
             * Format: date-time
             * @description Horodatage de la réponse, ISO 8601 UTC.
             */
            timestamp: string;
        };
        /**
         * PaginationMeta
         * @description Métadonnées de pagination accompagnant toute collection paginée.
         */
        PaginationMeta: {
            /**
             * Limit
             * @description Taille de page demandée, entre 1 et 1000 (défaut 100).
             */
            limit: number;
            /**
             * Offset
             * @description Décalage appliqué au début de la collection.
             */
            offset: number;
            /**
             * Total
             * @description Nombre total d'éléments disponibles pour la requête.
             */
            total: number;
        };
        /**
         * ReadingsPage
         * @description Page de mesures énergétiques accompagnée de ses métadonnées.
         */
        ReadingsPage: {
            /**
             * Items
             * @description Mesures de la page, triées par horodatage croissant.
             */
            items: components["schemas"]["EnergyReadingOut"][];
            /** @description Métadonnées de pagination de la requête. */
            meta: components["schemas"]["PaginationMeta"];
        };
        /**
         * SiteOut
         * @description Site industriel supervisé, miroir du site de l'API Mock IoT.
         */
        SiteOut: {
            /**
             * Capacity Kw
             * @description Puissance souscrite du site en kilowatts.
             */
            capacity_kw: number;
            /**
             * Location
             * @description Localisation géographique du site.
             */
            location: string;
            /**
             * Site Id
             * @description Identifiant technique du site.
             */
            site_id: string;
            /**
             * Site Name
             * @description Libellé du site affiché dans le dashboard.
             */
            site_name: string;
            /**
             * Site Type
             * @description Catégorie de site, par exemple usine ou entrepôt.
             */
            site_type: string;
            /**
             * Status
             * @description État d'exploitation du site remonté par la source.
             */
            status: string;
        };
        /**
         * TokenResponse
         * @description Jeton JWT délivré par le flux OAuth2 password.
         */
        TokenResponse: {
            /**
             * Access Token
             * @description Jeton JWT à placer dans l'en-tête Authorization.
             */
            access_token: string;
            /**
             * Expires In
             * @description Durée de validité du jeton en secondes.
             */
            expires_in: number;
            /**
             * Token Type
             * @description Schéma d'authentification à utiliser, toujours bearer.
             * @constant
             */
            token_type: "bearer";
        };
        /**
         * UserOut
         * @description Utilisateur authentifié tel qu'exposé par l'API.
         */
        UserOut: {
            /**
             * Role
             * @description Rôle applicatif : reader en lecture seule, writer en écriture.
             * @enum {string}
             */
            role: "reader" | "writer";
            /**
             * Username
             * @description Identifiant de connexion de l'utilisateur.
             */
            username: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_alerts_api_v1_alerts_get: {
        parameters: {
            query?: {
                /** @description Restreindre aux alertes de ce site. */
                site_id?: string | null;
                /** @description Restreindre aux alertes de cette gravité. */
                severity?: ("low" | "medium" | "high" | "critical") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertOut"][];
                };
            };
            /** @description Jeton JWT absent, expiré ou invalide. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Paramètres de requête invalides. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_token_api_v1_auth_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_create_token_api_v1_auth_token_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Identifiants invalides. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Paramètres de requête invalides. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    list_sites_api_v1_sites_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteOut"][];
                };
            };
            /** @description Jeton JWT absent, expiré ou invalide. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_site_api_v1_sites__site_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant du site. */
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteOut"];
                };
            };
            /** @description Jeton JWT absent, expiré ou invalide. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Site inconnu. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Paramètres de requête invalides. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_readings_api_v1_sites__site_id__readings_get: {
        parameters: {
            query: {
                /** @description Borne inférieure incluse de la fenêtre, ISO 8601 UTC. */
                start_time: string;
                /** @description Borne supérieure incluse de la fenêtre, ISO 8601 UTC. */
                end_time: string;
                /** @description Taille de page, entre 1 et 1000. */
                limit?: number;
                /** @description Décalage appliqué au début de la collection. */
                offset?: number;
            };
            header?: never;
            path: {
                /** @description Identifiant du site. */
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingsPage"];
                };
            };
            /** @description Jeton JWT absent, expiré ou invalide. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Site inconnu. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Paramètres de requête invalides. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_latest_reading_api_v1_sites__site_id__readings_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant du site. */
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnergyReadingOut"];
                };
            };
            /** @description Jeton JWT absent, expiré ou invalide. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Site inconnu. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Paramètres de requête invalides. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
