/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/predict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Prédire la consommation d'un site
         * @description Retourne la série prédite d'un site sur l'horizon demandé.
         */
        post: operations["predict_api_v1_predict_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Vérifier la disponibilité du service
         * @description Endpoint trivial, réellement implémenté : aucune dépendance externe.
         *
         *     Il ne consulte volontairement pas le registre. C'est la sonde de vivacité
         *     de l'hébergeur : la lier à MLflow ferait redémarrer un service en parfait
         *     état chaque fois que le registre tousse.
         */
        get: operations["get_health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ErrorResponse
         * @description Corps de réponse commun à toutes les erreurs du service d'inférence.
         */
        ErrorResponse: {
            /**
             * Detail
             * @description Message d'erreur destiné au consommateur de l'API.
             */
            detail: string;
        };
        /**
         * HealthOut
         * @description État de disponibilité du service d'inférence.
         */
        HealthOut: {
            /**
             * Status
             * @description Statut du service, ok s'il répond.
             * @constant
             */
            status: "ok";
            /**
             * Timestamp
             * Format: date-time
             * @description Horodatage de la réponse, ISO 8601 UTC.
             */
            timestamp: string;
        };
        /**
         * PredictionOut
         * @description Prévision complète renvoyée pour un site.
         */
        PredictionOut: {
            /**
             * Generated At
             * Format: date-time
             * @description Horodatage de production de la prévision, ISO 8601 UTC.
             */
            generated_at: string;
            /**
             * Model Version
             * @description Tag MLflow du modèle ayant servi la réponse.
             */
            model_version: string;
            /**
             * Points
             * @description Série prédite, triée par horodatage croissant.
             */
            points: components["schemas"]["PredictionPoint"][];
            /**
             * Site Id
             * @description Identifiant du site prédit.
             */
            site_id: string;
        };
        /**
         * PredictionPoint
         * @description Point de la série prédite, avec son intervalle de confiance.
         */
        PredictionPoint: {
            /**
             * Lower Bound Kw
             * @description Borne basse de l'intervalle de confiance, nulle si non calculée.
             */
            lower_bound_kw: number | null;
            /**
             * Predicted Consumption Kw
             * @description Puissance prédite en kilowatts.
             */
            predicted_consumption_kw: number;
            /**
             * Timestamp
             * Format: date-time
             * @description Horodatage du point prédit, ISO 8601 UTC.
             */
            timestamp: string;
            /**
             * Upper Bound Kw
             * @description Borne haute de l'intervalle de confiance, nulle si non calculée.
             */
            upper_bound_kw: number | null;
        };
        /**
         * PredictionRequest
         * @description Demande de prévision de consommation pour un site.
         */
        PredictionRequest: {
            /**
             * Horizon Hours
             * @description Profondeur de la prévision en heures, entre 1 et 48.
             * @default 24
             */
            horizon_hours: number;
            /**
             * Site Id
             * @description Identifiant du site à prédire.
             */
            site_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    predict_api_v1_predict_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PredictionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionOut"];
                };
            };
            /** @description Site inconnu du modèle. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Paramètres de requête invalides. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Aucun modèle résolu par le registre. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
}
